# Generated by Django 2.0 on 2020-11-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='comment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
