# Generated by Django 2.0 on 2020-11-20 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_task_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task',
            new_name='task_value',
        ),
    ]
